-- =============================================
-- Auction Service 임시 데이터 (biddy_auction DB)
-- v2: 도메인 순수성 설계 (productId만 보관, 상품정보 미저장)
-- =============================================

\c biddy_auction;

-- 기존 테이블 초기화
DROP TABLE IF EXISTS auction_watch, bid, auction;

-- auction 테이블 생성
CREATE TABLE auction (
    auction_id      VARCHAR(20)   NOT NULL PRIMARY KEY,
    product_id      UUID          NOT NULL UNIQUE,
    seller_id       BIGINT        NOT NULL,
    start_price     BIGINT        NOT NULL,
    min_increment   BIGINT        NOT NULL,
    current_bid     BIGINT        NOT NULL DEFAULT 0,
    bid_count       INTEGER       NOT NULL DEFAULT 0,
    watcher_count   INTEGER       NOT NULL DEFAULT 0,
    status          VARCHAR(10)   NOT NULL DEFAULT 'LIVE'
                    CHECK (status IN ('LIVE','ENDED')),
    starts_at       TIMESTAMP(6),
    ends_at         TIMESTAMP(6)  NOT NULL,
    winner_id       BIGINT,
    winning_bid_id  BIGINT,
    created_at      TIMESTAMP(6)  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP(6)  NOT NULL DEFAULT NOW()
);

-- bid 테이블 생성
CREATE TABLE bid (
    bid_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id  VARCHAR(20)   NOT NULL,
    bidder_id   BIGINT        NOT NULL,
    amount      BIGINT        NOT NULL,
    bid_at      TIMESTAMP(6)  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bid_auction_bid_at  ON bid (auction_id, bid_at DESC);
CREATE INDEX idx_bid_auction_amount  ON bid (auction_id, amount DESC);

-- auction_watch 테이블 생성
CREATE TABLE auction_watch (
    watch_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id  VARCHAR(20)   NOT NULL,
    member_id   BIGINT        NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_watch_auction_member UNIQUE (auction_id, member_id)
);

-- =============================================
-- LIVE 경매 시드 데이터 (6건)
-- product_id는 Product Service의 UUID를 참조
-- =============================================
INSERT INTO auction (auction_id, product_id, seller_id,
                     start_price, min_increment, current_bid, bid_count, watcher_count,
                     status, starts_at, ends_at, created_at, updated_at)
VALUES
-- 나이키 덩크 (Product에서 관리하는 상품)
('A-FNF97', 'a1b2c3d4-1111-4000-8000-000000000001', 1,
 400000, 20000, 720000, 6, 88,
 'LIVE', NOW() - INTERVAL '3 days', NOW() + INTERVAL '2 days', NOW() - INTERVAL '3 days', NOW()),

-- 에어 조던 1
('A-AJ1HI', 'a1b2c3d4-2222-4000-8000-000000000002', 2,
 800000, 50000, 1500000, 12, 210,
 'LIVE', NOW() - INTERVAL '5 days', NOW() + INTERVAL '1 day', NOW() - INTERVAL '5 days', NOW()),

-- 뉴발란스 550
('A-NB550', 'a1b2c3d4-3333-4000-8000-000000000003', 3,
 120000, 10000, 180000, 4, 45,
 'LIVE', NOW() - INTERVAL '1 day', NOW() + INTERVAL '5 days', NOW() - INTERVAL '1 day', NOW()),

-- 슈프림 박스로고
('A-SUP23', 'a1b2c3d4-4444-4000-8000-000000000004', 1,
 500000, 30000, 650000, 3, 120,
 'LIVE', NOW() - INTERVAL '2 days', NOW() + INTERVAL '3 days', NOW() - INTERVAL '2 days', NOW()),

-- 롤렉스 서브마리너
('A-RP001', 'a1b2c3d4-5555-4000-8000-000000000005', 4,
 12000000, 500000, 15500000, 5, 340,
 'LIVE', NOW() - INTERVAL '1 day', NOW() + INTERVAL '7 days', NOW() - INTERVAL '1 day', NOW()),

-- 맥북 프로
('A-MAC15', 'a1b2c3d4-6666-4000-8000-000000000006', 5,
 3000000, 100000, 3500000, 3, 95,
 'LIVE', NOW() - INTERVAL '2 days', NOW() + INTERVAL '4 days', NOW() - INTERVAL '2 days', NOW());

-- =============================================
-- ENDED 경매 시드 데이터 (4건, winnerId/winningBidId 포함)
-- =============================================
INSERT INTO auction (auction_id, product_id, seller_id,
                     start_price, min_increment, current_bid, bid_count, watcher_count,
                     status, starts_at, ends_at, winner_id, winning_bid_id, created_at, updated_at)
VALUES
-- 이지 부스트 (낙찰: bidder 10, bid_id는 아래 INSERT 후 확인)
('A-YZY01', 'a1b2c3d4-7777-4000-8000-000000000007', 2,
 300000, 20000, 520000, 8, 150,
 'ENDED', NOW() - INTERVAL '8 days', NOW() - INTERVAL '1 day', 10, NULL,
 NOW() - INTERVAL '8 days', NOW() - INTERVAL '1 day'),

-- 루이비통 키폴 (낙찰: bidder 14)
('A-LV001', 'a1b2c3d4-8888-4000-8000-000000000008', 3,
 1500000, 100000, 2200000, 6, 180,
 'ENDED', NOW() - INTERVAL '10 days', NOW() - INTERVAL '2 days', 14, NULL,
 NOW() - INTERVAL '10 days', NOW() - INTERVAL '2 days'),

-- PS5 Pro (낙찰: bidder 11)
('A-PS5PR', 'a1b2c3d4-9999-4000-8000-000000000009', 4,
 600000, 30000, 850000, 7, 200,
 'ENDED', NOW() - INTERVAL '7 days', NOW() - INTERVAL '3 days', 11, NULL,
 NOW() - INTERVAL '7 days', NOW() - INTERVAL '3 days'),

-- 구찌 마몬트 (낙찰: bidder 22)
('A-GUC01', 'a1b2c3d4-aaaa-4000-8000-000000000010', 5,
 1000000, 50000, 1350000, 5, 95,
 'ENDED', NOW() - INTERVAL '12 days', NOW() - INTERVAL '5 days', 22, NULL,
 NOW() - INTERVAL '12 days', NOW() - INTERVAL '5 days');


-- =============================================
-- bid 테이블 시드 데이터
-- =============================================

-- A-FNF97 입찰 내역 (6건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-FNF97', 10, 420000, NOW() - INTERVAL '3 days' + INTERVAL '1 hour'),
('A-FNF97', 11, 450000, NOW() - INTERVAL '3 days' + INTERVAL '3 hours'),
('A-FNF97', 12, 500000, NOW() - INTERVAL '2 days' + INTERVAL '2 hours'),
('A-FNF97', 10, 550000, NOW() - INTERVAL '2 days' + INTERVAL '5 hours'),
('A-FNF97', 13, 650000, NOW() - INTERVAL '1 day' + INTERVAL '4 hours'),
('A-FNF97', 11, 720000, NOW() - INTERVAL '6 hours');

-- A-AJ1HI 입찰 내역 (12건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-AJ1HI', 14, 850000,  NOW() - INTERVAL '5 days' + INTERVAL '2 hours'),
('A-AJ1HI', 15, 900000,  NOW() - INTERVAL '5 days' + INTERVAL '5 hours'),
('A-AJ1HI', 16, 950000,  NOW() - INTERVAL '4 days' + INTERVAL '1 hour'),
('A-AJ1HI', 14, 1000000, NOW() - INTERVAL '4 days' + INTERVAL '6 hours'),
('A-AJ1HI', 17, 1050000, NOW() - INTERVAL '3 days' + INTERVAL '3 hours'),
('A-AJ1HI', 15, 1100000, NOW() - INTERVAL '3 days' + INTERVAL '8 hours'),
('A-AJ1HI', 18, 1150000, NOW() - INTERVAL '2 days' + INTERVAL '2 hours'),
('A-AJ1HI', 14, 1200000, NOW() - INTERVAL '2 days' + INTERVAL '7 hours'),
('A-AJ1HI', 17, 1250000, NOW() - INTERVAL '1 day' + INTERVAL '1 hour'),
('A-AJ1HI', 15, 1350000, NOW() - INTERVAL '1 day' + INTERVAL '5 hours'),
('A-AJ1HI', 18, 1400000, NOW() - INTERVAL '12 hours'),
('A-AJ1HI', 14, 1500000, NOW() - INTERVAL '3 hours');

-- A-NB550 입찰 내역 (4건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-NB550', 11, 130000, NOW() - INTERVAL '1 day' + INTERVAL '2 hours'),
('A-NB550', 19, 140000, NOW() - INTERVAL '1 day' + INTERVAL '6 hours'),
('A-NB550', 20, 160000, NOW() - INTERVAL '18 hours'),
('A-NB550', 11, 180000, NOW() - INTERVAL '8 hours');

-- A-SUP23 입찰 내역 (3건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-SUP23', 16, 530000, NOW() - INTERVAL '2 days' + INTERVAL '4 hours'),
('A-SUP23', 21, 580000, NOW() - INTERVAL '1 day' + INTERVAL '2 hours'),
('A-SUP23', 16, 650000, NOW() - INTERVAL '10 hours');

-- A-RP001 입찰 내역 (5건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-RP001', 22, 12500000, NOW() - INTERVAL '1 day' + INTERVAL '1 hour'),
('A-RP001', 23, 13000000, NOW() - INTERVAL '1 day' + INTERVAL '4 hours'),
('A-RP001', 22, 14000000, NOW() - INTERVAL '20 hours'),
('A-RP001', 24, 14500000, NOW() - INTERVAL '12 hours'),
('A-RP001', 23, 15500000, NOW() - INTERVAL '5 hours');

-- A-MAC15 입찰 내역 (3건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-MAC15', 25, 3100000, NOW() - INTERVAL '2 days' + INTERVAL '3 hours'),
('A-MAC15', 26, 3300000, NOW() - INTERVAL '1 day' + INTERVAL '6 hours'),
('A-MAC15', 25, 3500000, NOW() - INTERVAL '14 hours');

-- A-YZY01 종료 경매 입찰 내역 (8건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-YZY01', 10, 320000, NOW() - INTERVAL '8 days' + INTERVAL '2 hours'),
('A-YZY01', 12, 340000, NOW() - INTERVAL '7 days' + INTERVAL '1 hour'),
('A-YZY01', 13, 360000, NOW() - INTERVAL '6 days' + INTERVAL '5 hours'),
('A-YZY01', 10, 380000, NOW() - INTERVAL '5 days' + INTERVAL '3 hours'),
('A-YZY01', 15, 420000, NOW() - INTERVAL '4 days' + INTERVAL '2 hours'),
('A-YZY01', 12, 450000, NOW() - INTERVAL '3 days' + INTERVAL '6 hours'),
('A-YZY01', 13, 480000, NOW() - INTERVAL '2 days' + INTERVAL '4 hours'),
('A-YZY01', 10, 520000, NOW() - INTERVAL '1 day' - INTERVAL '2 hours');

-- A-LV001 종료 경매 입찰 내역 (6건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-LV001', 14, 1600000, NOW() - INTERVAL '10 days' + INTERVAL '3 hours'),
('A-LV001', 16, 1700000, NOW() - INTERVAL '9 days' + INTERVAL '5 hours'),
('A-LV001', 14, 1800000, NOW() - INTERVAL '7 days' + INTERVAL '2 hours'),
('A-LV001', 20, 1900000, NOW() - INTERVAL '5 days' + INTERVAL '6 hours'),
('A-LV001', 16, 2100000, NOW() - INTERVAL '3 days' + INTERVAL '4 hours'),
('A-LV001', 14, 2200000, NOW() - INTERVAL '2 days' - INTERVAL '1 hour');

-- A-PS5PR 종료 경매 입찰 내역 (7건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-PS5PR', 11, 630000, NOW() - INTERVAL '7 days' + INTERVAL '2 hours'),
('A-PS5PR', 19, 660000, NOW() - INTERVAL '6 days' + INTERVAL '4 hours'),
('A-PS5PR', 25, 700000, NOW() - INTERVAL '5 days' + INTERVAL '1 hour'),
('A-PS5PR', 11, 730000, NOW() - INTERVAL '4 days' + INTERVAL '5 hours'),
('A-PS5PR', 26, 780000, NOW() - INTERVAL '4 days' + INTERVAL '8 hours'),
('A-PS5PR', 19, 820000, NOW() - INTERVAL '3 days' - INTERVAL '6 hours'),
('A-PS5PR', 11, 850000, NOW() - INTERVAL '3 days' - INTERVAL '2 hours');

-- A-GUC01 종료 경매 입찰 내역 (5건)
INSERT INTO bid (auction_id, bidder_id, amount, bid_at) VALUES
('A-GUC01', 21, 1050000, NOW() - INTERVAL '12 days' + INTERVAL '4 hours'),
('A-GUC01', 22, 1100000, NOW() - INTERVAL '10 days' + INTERVAL '2 hours'),
('A-GUC01', 21, 1200000, NOW() - INTERVAL '8 days' + INTERVAL '6 hours'),
('A-GUC01', 24, 1300000, NOW() - INTERVAL '6 days' + INTERVAL '3 hours'),
('A-GUC01', 22, 1350000, NOW() - INTERVAL '5 days' - INTERVAL '1 hour');


-- =============================================
-- auction_watch 테이블 시드 데이터
-- =============================================
INSERT INTO auction_watch (auction_id, member_id, created_at) VALUES
-- 사용자 10번
('A-FNF97', 10, NOW() - INTERVAL '3 days'),
('A-AJ1HI', 10, NOW() - INTERVAL '4 days'),
('A-RP001', 10, NOW() - INTERVAL '1 day'),

-- 사용자 11번
('A-FNF97', 11, NOW() - INTERVAL '2 days'),
('A-NB550', 11, NOW() - INTERVAL '1 day'),
('A-SUP23', 11, NOW() - INTERVAL '2 days'),
('A-MAC15', 11, NOW() - INTERVAL '1 day'),

-- 사용자 14번
('A-AJ1HI', 14, NOW() - INTERVAL '5 days'),
('A-RP001', 14, NOW() - INTERVAL '1 day'),
('A-LV001', 14, NOW() - INTERVAL '9 days'),

-- 사용자 42번 (테스트용)
('A-FNF97', 42, NOW() - INTERVAL '1 day'),
('A-AJ1HI', 42, NOW() - INTERVAL '2 days'),
('A-NB550', 42, NOW() - INTERVAL '6 hours');
