apiVersion: v1
kind: Namespace
metadata:
  name: biddy-services
  labels:
    name: biddy-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: biddy-gateway
  labels:
    name: biddy-gateway
