apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biddy

resources:
  - namespace.yaml
  - common/configmap.yaml
  - external-services/postgres-external.yaml
  - external-services/redis-external.yaml
  - external-services/kafka-external.yaml
  - external-services/elasticsearch-external.yaml
  - discovery/deployment.yaml
  - discovery/service.yaml
  - config/deployment.yaml
  - config/service.yaml
  - apigateway/deployment.yaml
  - apigateway/service.yaml
  - apigateway/networkpolicy.yaml
  - member/deployment.yaml
  - member/service.yaml
  - member/networkpolicy.yaml
  - product/deployment.yaml
  - product/service.yaml
  - product/networkpolicy.yaml
  - search/deployment.yaml
  - search/service.yaml
  - order/deployment.yaml
  - order/service.yaml
  - order/networkpolicy.yaml
  - auction/deployment.yaml
  - auction/service.yaml
  - auction/networkpolicy.yaml
  - payment/deployment.yaml
  - payment/service.yaml
  - payment/settlement-cronjob.yaml
  - chat/deployment.yaml
  - chat/service.yaml
  - chatbot/deployment.yaml
  - chatbot/service.yaml
  - ingress.yaml
